### PR TITLE
Add symfony 5 support

### PR DESCRIPTION
**Pull request by alexander-schranz**
This is still in process.

# TODO

 - [x] Use symfony phpunit bridge to support this wide range of symfony and php versions
 - [x] Use webmozart/assert instead of phpunit assert for supporting different version of php and symfony
 - [x] Update Symfony EventDispatcher
 - [x] Update Symfony Console
 - [x] Make tests green 🙏

### CODE REVIEW

**Comment by dantleech** [comment]
I think we can bump the minimum PHP requirement to 7.2 - this PR introduces support for Symfony 5 which has that requirement, and anybody who wants to use Symfony 4 will just get the previous version of this package.

That should solve some of the build issues (if not all of them)!

**Comment by dbu** [comment]
seems fair to me. you could still support php 7.0 or 7.1 with older symfony versions, but i don't think that is an important consideration - the shell seems to be quite stable, so no problem for people stuck on old php to use an old version.

**Comment by alexander-schranz** [comment]
@dantleech do you have maybe a hint what could cause the errors which are appearing in [embedded](https://travis-ci.org/phpcr/phpcr-shell/jobs/646848999?utm_medium=notification&utm_source=github_status) and [standalone](https://travis-ci.org/phpcr/phpcr-shell/jobs/646848998?utm_medium=notification&utm_source=github_status) tests? I'm very unfamiliar with behat 🙈

**Comment by dantleech** [comment]
hmm, Jackrabbit just returns 503 both with 2.18 and 2.8 - @dbu do you recall what error you had with the ODM?

**Comment by alexander-schranz** [comment]
@dantleech downgraded the travis dist and it seems to work now :)

**Comment by dantleech** [comment]
> downgraded the travis dist and it should work now I hope 

Fixed forever! :smile:

**Comment by alexander-schranz** [comment]
@dantleech sadly php 7.2 get stuck on the following tests:

```
Feature: Edit a node type

    In order to modify a node type definition

    As a user that is logged into the shell

    I should be able to run a command which launches an external editor to edit the CND as a text file
```

if I read that it sounds like me the editor is really started and never closed and thats why it don't continue or what do you think?

**Comment by alexander-schranz** [comment]
@dantleech Finally I found the working prefer lowest dependencies.

Yeah

**Comment by dantleech** [comment]
:tada: well done :)

**Comment by dantleech** [comment]
Thanks again, let me know when you want a tag

**Comment by alexander-schranz** [comment]
@dantleech Tag would be great or atleast an update of the branch alias in the composer.json :)

**Comment by dantleech** [comment]
Can you assert that master works with f.e. Sulu?

**Comment by alexander-schranz** [comment]
@dantleech not yet there still to many dependencies which are not yet compatible with symfony 5 🙈

**Comment by alexander-schranz** [comment]
@dantleech tested can be released :)

**Comment by alexander-schranz** [comment]
@dantleech could we create a release for this and the [phpcr-migrations-bundle](https://github.com/phpcr/phpcr-shell/pull/204)?

**Comment by dantleech** [comment]
Release 1.2.0 :tada: sorry for the delay

**Comment by dantleech** [comment]
Also 1.2.0 of migrations

**Comment by alexander-schranz** [comment]
@dantleech Thank you 🎉

**Pull request merged**
