### PR TITLE
Query result formatter: remove column 'Index' from table head

### PR DESCRIPTION
**Pull request by middlebrain**
There is no data column for the head column 'Index'.

### CODE REVIEW

**Comment by dbu** [comment]
are you sure that there never is? index would be for multivalue properties. have you tried with multivalue properties? if you did and saw nothing, then it might not have been implemented...

**Comment by middlebrain** [comment]
At the moment, the column `Index` exists on the table head only.

In the foreach loop there is no code, which collect data for this column:

https://github.com/phpcr/phpcr-shell/blob/bc9b29ff4536ac7d27c3188a48c48d04e68cdea4/src/PHPCR/Shell/Console/Helper/ResultFormatterHelper.php#L69-L78

The table header and the rest of the table are therefore out of sync.

Multivalue properties in the `QueryResult` are either empty or stringified (depending on the repository implementation).

**Comment by dbu** [comment]
thanks, then this makes sense.

should we tag a new release with these fixes? or is there more to come very soon? (we can always tag another version in a week or 2, there is no shortage of version numbers ;-) but if you intend to fix more stuff this week, or are aware of problems, we could delay the release a bit)

**Comment by middlebrain** [comment]
One fix is still on the way.

**Pull request merged**
