### PR TITLE
Add php 7.x to the test matrix

### PR DESCRIPTION
**Pull request by middlebrain**
Fix behat runtime errors by using php 7.x
Travis: build with 7.x

### CODE REVIEW

**Comment by dbu** [comment]
thanks a ton for picking this up! and it seems to look like there are no issues with php 7.

i let styleci fix the styling in the master branch. can you please rebase?

the test that fails is "Execute the note-type show command" and it looks like the ordering of that node type definition changed in jackrabbit. i am confident that the order is not relevant - can you please change the order in what we expect?

**Comment by dbu** [comment]
re the failing test: sorry, i saw you did a separate pull request. the other PR is merged, so when you rebase this on master, it should get green \o/

**Comment by middlebrain** [comment]
> re the failing test: sorry, i saw you did a separate pull request.

My bad. Looking back, I should have better combined the two pull requests into one.

> the other PR is merged, so when you rebase this on master, it should get green \o/

Rebase made.

**Comment by dbu** [comment]
great, thanks a lot!

do you want to become a contributor for this project? as we currently don't have an active maintainer, it would be great to have somebody taking care of it a bit.

**Comment by middlebrain** [comment]
As an active user of php-shell, I just wanted to fix the most annoying bugs.

There are more things that bother me. But I don't have time to dive deeper into it right now.

**Pull request merged**
