### PR TITLE
Command node:list (ls): Fix wrong node counter

### PR DESCRIPTION
**Pull request by middlebrain**
The displayed node counter for the 'ls' command is always set to 1.

### CODE REVIEW

**Comment by dantleech** [comment]
Thanks for the PR, I'm not really in a position to test these changes at the moment as I don't do any development with PHPCR currently and I can't get Jackrabbit working locally for whatever reason. So I would trust you that this change works.

The tests are failing apparently due to unrelated changes in other PHPCR libraries. Would be good to update the test expectations and make the build green before merging this.

**Comment by dbu** [comment]
can you rebase this on master please?

is it possible to write a test for this that could make sure the edge cases are now handled correctly? i notice that the counter is not right in the `foreach($nodes as $node)` line, so i guess there are lines we do not want to count...

**Comment by middlebrain** [comment]
I have reworked the fix a little bit and also added two tests. Node counting works now in the same way as property counting in the `PHPCR/Shell/Console/Command/Phpcr/NodeListCommand::renderProperties` function.

**Comment by dantleech** [comment]
Nice work :)

**Pull request merged**
