### PR TITLE
Add support for symfony 5

### PR DESCRIPTION
**Pull request by alexander-schranz**

### CODE REVIEW

**Comment by dantleech** [comment]
Note that there are BC breaks in SF 5.0 (e.g. the Process component no longer accepts a string as it's first argument), and the tests are not running on this PR.

**Comment by alexander-schranz** [comment]
@dantleech thx for the response, will have a look at that later.

**Comment by dbu** [comment]
oops. should i revert the merge?

**Comment by dantleech** [comment]
If it hasn't been tested might be safer - I merged 5.0 support on Phpbench then realised that it wasn't compatible and reverted. 

On 20 November 2019 17:11:41 CET, David Buchmann <notifications@github.com> wrote:
>oops. should i revert the merge?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpcr/phpcr-shell/pull/201#issuecomment-556077844

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dbu** [comment]
@alexander-schranz did you test it manually? any chance you could make the ci work?

**Comment by dantleech** [comment]
SF 5.0 was released about an hour ago :)

On 21 November 2019 09:36:34 CET, David Buchmann <notifications@github.com> wrote:
>@alexander-schranz did you test it manually? any chance you could make
>the ci work?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpcr/phpcr-shell/pull/201#issuecomment-556977485

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dbu** [comment]
i reverted in #202 until its sorted out. more than happy to merge a thing that upgrades once we are sure we don't break stuff.

**Comment by alexander-schranz** [comment]
@dantleech  where is the Process Component used in this phpcr shell? Couldn't find any appearance of it https://github.com/phpcr/phpcr-shell/search?utf8=%E2%9C%93&q=Process&type=

**Pull request merged**
